services:
  init:
    image: alpine:latest
    command: ["echo", "Initialization complete"]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/app/public
    depends_on:
      django:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s
    networks:
      - app-network

  django:
    build: .
    command: python myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=footballdb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=123
      - DATABASE_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/teams/"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=footballdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./footballdb_dump.sql:/docker-entrypoint-initdb.d/footballdb_dump.sql
    depends_on:
      init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "footballdb"]
      interval: 1s
      timeout: 1s
      retries: 8
      start_period: 3s
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
